language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -r requirements_dev.txt --use-mirrors
    - python setup.py install
script: python setup.py nosetests
branches:
    only:
        - master
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
