sudo: required
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

install:
    - python setup.py install
script: nosetests
branches:
    only:
        - master
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/requirements27_dev.txt; fi
    - pip install codecov
after_success:
    - codecov